apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-config
  namespace: vitor-esser-blog
data:
  BLOG_TITLE: 'The blog of Vitor Esser'
  BLOG_SUBTITLE: 'My adventures in GitOps and ArgoCD'
  AUTHOR: 'Vitor Esser'
  THEME: 'dark'
  VERSION: '1.0.0'
